---
- name: "Install httpd"
  package:
          name: "{{ software_name }}"
          state: present

- name: "Install httpd"
  package:
          name: "{{ software_php }}"
          state: present

- name: "Check Service is running"
  service:
          name: "{{ software_name }}"
          state: started
          enabled: yes

- name: "Create the directory for doc root"
  file:
          state: directory
          path: "{{ doc_root }}"

- name: "Configure the http"
  template:
          src: "httpd.conf.j2"
          dest: "/etc/httpd/conf.d/custome.conf"
  notify:
          - "Restart httpd"

- name: "Copy web pages"
  copy:
          src: "./files/index.php"
          dest: "{{ doc_root }}/index.php"
